#!/bin/bash
#ssh-keygen -t rsa -b 4096 -C "note"
#ssh-keygen -f /c/home/caleb/.ssh/id_ed25519_no_pass -o -a 100 -t ed25519 -C "note"
#ssh-keygen -f /c/home/caleb/.ssh/id_ed25519_w_passphrase -o -a 100 -t ed25519 -C "note"
