#!/bin/bash
git add *
git commit -m "updates to template files"

export REPOS=/g/dev/calebcodesit/repos

cd $REPOS/ssh
ssh-agent bash -c 'ssh-add /g/dev/calebcodesit/.ssh/id_rsa; git push origin master'
